export default class zc_config {
    static firest: { [key: string]: string } = {
        "xiyiji1": "icon/xjy2",
        "xie": "icon/x2",
        "yu": "icon/y2",
        "beizi": "icon/be2",
        "jianpan": "icon/jp2",
        "tong": "icon/lj2",
        "qiang": "icon/qian2",
        "yifu": "icon/yinf2",
        "guizi": "icon/cg2",
        "koudai": "icon/koud2",
        "shouji1": "icon/shouj2",
    }
    static firest_qp: { [key: string]: string } = {
        "xiyiji1": "洗的是你的衣服,不是我的",
        "xie": "鞋垫你都要",
        "yu": "玩具是小表弟家的,一定是他零花钱忘拿咯",
        "beizi": "这是攒起来给你买礼物的",
        "jianpan": "这是给儿子买玩具留的呐",
        "tong": "一定是打扫卫生时,不小心掉进去的",
        "qiang": "肯定是装修师傅的钱忘拿了",
        "yifu": "这都被你发现了",
        "guizi": "这样晚上睡觉才不会失眠",
        "koudai": "是买菜剩的钱",
        "shouji1": "我的快乐没有了",
        "end": "今晚就给老娘跪着",
    }
    static firest_tip: { [key: string]: string } = {
        "tong": "点击垃圾桶",
        "xie": "点击地上的鞋子",
        "guizi": "点击床头柜",
        "jianpan": "左移柜子",
        "beizi": "点击床上的被子",
        "yu": "点击地上的鱼玩偶",
        "qiang": "拖动地下的锤子砸墙",
        "koudai": "点击强哥裤子上的口袋",
        "yifu": "拖动地下的撑衣杆把窗外衣服取下",
        "shouji1": "移动床上的手机到强哥脸上",
        "xiyiji1": "断开洗衣机电源再打开洗衣机门",
    }
    static lv2: { [key: string]: string } = {
        "gou": "icon/gou",
        "chuang": "icon/chuang",
        "dt": "icon/ditan",
        "xiong": "icon/xiong",
        "liul": "icon/liul",
        "nv": "icon/nvlian",
        "nan": "icon/nan",
        "gui": "icon/gui",
        "ping": "icon/ping",
        "chout": "icon/chouti",
        "hua": "icon/he",
    }
    static lv2qp: { [key: string]: string } = {
        "gou": "汪汪~|3",
        "chuang": "大风吹来的|1",
        "dt": "地板也要护肤|1",
        "xiong": "买玩具送面膜|1",
        "liul": "这样更有味|1",
        "nv": "今天也是精致女孩|1",
        "nan": "你干嘛~哎呀|2",
        "gui": "这不是没地方放了嘛|1",
        "ping": "这都被你找到！厉害|1",
        "chout": "原来这里还有啊|1",
        "hua": "这是压箱底的|1",
    }
    static lv2tip: { [key: string]: string } = {
        "gou": "点击狗狗脸上的面膜",
        "chuang": "拉开窗帘",
        "dt": "点击地上的地毯",
        "xiong": "点击柜子上的小熊",
        "liul": "拖动桌面上的菜刀打开榴莲",
        "nv": "点击女主脸上的面膜",
        "nan": "点击男主脸上的面膜",
        "gui": "点击柜子",
        "ping": "点击墙上的瓶子",
        "chout": "点击桌子下的右边抽屉",
        "hua": "挪开花瓶",
    }


    static lv3: { [key: string]: string } = {
        "xiang": "icon/daoju1|3",
        "niao": "icon/daoju2|5",
        "fenshen": "icon/daoju3|275",
        "ying": "icon/daoju3b|1",
        "chuang": "icon/daoju4|3",
        "men": "icon/daoju5|20",
        "yushi": "icon/daoju6|3",
        "diban": "icon/daoju7|5",
        "chout": "icon/daoju8|3",
        "beizi": "icon/daoju9|1",
        "bihua": "icon/daoju10|3000",
        "yigui": "icon/daoju11|5",
        "jingzi": "icon/daoju12|10",
    }
    static lv3qp: { [key: string]: string } = {
        "xiang": "是给朕上贡来的。|1",
        "niao": "他们是来护驾的。|1",
        "fenshen": "朕也想学忍术来对付后宫三千佳丽。|1",
        "ying": "有刺客！|1",
        "chuang": "她们是来修窗户的。|1",
        "men": "都拉肚子来上厕所。|1",
        "yushi": "她们是来修马桶。|1",
        "diban": "地板坏了,来修地板的。|1",
        "chout": "朕和他们玩躲猫猫。|1",
        "beizi": "苏公公正想帮朕暖床。|1",
        "bihua": "一张全家福而已。|1",
        "yigui": "来给朕整理衣柜的。|1",
        "jingzi": "镜花水月。|1",
    }
    static lv3tip: { [key: string]: string } = {
        "chuang": "1.点击窗帘",
        "men": "2.点击木门",
        "yushi": "3.点击浴布",
        "diban": "4.拖动地板",
        "chout": "5.点击柜子",
        "yigui": "6.点击衣柜",
        "jingzi": "7.点击镜子",
        "bihua": "8.点击墙上的画像",
        "beizi": "9.向下拖动床上的被子",
        "xiang": "10.移动地上的钥匙打开宝箱",
        "niao": "11.拖动桌面上的鸽子放出窗外",
        "fenshen": "13.点击床上的影子后\n拖动地上分身术到忍者上",
    }


    static lv4: { [key: string]: string } = {
        "biaoqing": "icon/daoju1|痴汉表情",
        "shutiao": "icon/daoju2|床上薯条",
        "shouzhi": "icon/daoju3|兰花指",
        "biao": "icon/daoju4|男士手表",
        "yifu": "icon/daoju5|男扮女装",
        "baoyang": "icon/daoju6|不懂保养",
        "zuozi": "icon/daoju7|粗鲁坐姿",
        "tuomao": "icon/daoju8|脱毛膏",
        "siwa": "icon/daoju9|穿丝袜",
        "zhijia": "icon/daoju10|涂指甲油",
    }
    static lv4tip: { [key: string]: string } = {
        "a": "第一个场景",
        "chuang": "1.丝袜",
        "men": "2.男生的脚",
        "yushi": "3.女生的坐姿",
        "diban": "4.脱毛膏",
        "chout": "5.女生手上的护肤品",
        "b": "点击镜子进入第二个场景",
        "yigui": "6.薯条",
        "jingzi": "7.女生的表情",
        "bihua": "8.男生的手指",
        "beizi": "9.男生的手表",
        "xiang": "10.男生的裙子",
    }


    static lv5: { [key: string]: string } = {
        "dai": "icon/daoju1|绑带",
        "pai": "icon/daoju2|胸牌",
        "duo": "icon/daoju3|兔耳朵",
        "zui": "icon/daoju4|吊坠",
        "lian": "icon/daoju5|手链",
        "shou": "icon/daoju6|匕首",
        "yi": "icon/daoju7|黄色上衣",
        "jing": "icon/daoju8|墨镜",
        "zi": "icon/daoju9|靴子",
        "jia": "icon/daoju10|涂指甲",
    }
    static lv5tip: { [key: string]: string } = {
        "a": "第一个女生",
        "chuang": "1.绑带",
        "men": "2.胸牌",
        "b": "第二个女生",
        "yushi": "3.兔耳朵",
        "diban": "4.吊坠",
        "chout": "5.手链",
        "yigui": "6.匕首",
        "jingzi": "7.黄色上衣",
        "c": "第三个女生",
        "bihua": "8.墨镜",
        "beizi": "9.靴子",
        "xiang": "10.涂指甲",
    }
    static lv16: { [key: string]: string } = {
        "shang": "icon/daoju1|阁楼上",
        "gui": "icon/daoju2|门边柜子",
        "chuang": "icon/daoju3|榻榻米",
        "qiang": "icon/daoju4|墙柜",
        "nan": "icon/daoju5|强哥怀里",
        "hua": "icon/daoju6|画中",
        "men": "icon/daoju7|门后",
        "ping": "icon/daoju8|花瓶里",
        "qiu": "icon/daoju9|地球仪",
        "nv": "icon/daoju10|大嫂怀里",
    }
    static lv16tip: { [key: string]: string } = {
        "shang": "1.阁楼上",
        "gui": "2.门边柜子",
        "chuang": "3.榻榻米",
        "qiang": "4.墙柜",
        "nan": "5.强哥怀里",
        "hua": "6.画中",
        "men": "7.门后",
        "ping": "8.花瓶里",
        "qiu": "9.地球仪",
        "nv": "10.大嫂怀里",
    }
    static lv21tip: { [key: string]: string } = {
        "a": " 1. 围裙上的图案",
        "b": " 2. 围裙的颜色",
        "c": " 3. 桌子上面的颜色",
        "d": " 4. (两个)鞋带颜色",
        "e": " 5.天花的指示灯",
        "f": " 6. 客人衣领颜色",
    }
}
